project_id = "xdyumezeouultnxssnlc"

[functions.api4com-webhook]
verify_jwt = false

[functions.bitrix24-webhook]
verify_jwt = false

[functions.bitrix24-install]
verify_jwt = false

[functions.test-connection]
verify_jwt = false

[functions.api4com-setup]
verify_jwt = false
